# Create full conda environment for development, including some useful tools
name: devel
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - numpy
  - matplotlib
  - requests
  - protobuf
  - netcdf4
  - metpy
  - jupyter
  - xarray
  - cartopy
  - siphon
  - xarray
  - pip
  - pydap
  - nc-time-axis
  - ipywidgets
